### ISSUE TITLE
rspectacles/adapter/redis_logger.rb:42:in `format_example': undefined method `status' for #<Hash:xxx> (NoMethodError)

### ISSUE THREAD

**Issue by lluchez** [g2crowd/rspectacles#5]
Hi,

I just tried to install this Gem in my project and I'm getting the following error when running rspec:
```
/Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspectacles-0.1.3/lib/rspectacles/adapter/redis_logger.rb:42:in `format_example': undefined method `status' for #<Hash:0x007fe2f4d4b028> (NoMethodError)
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspectacles-0.1.3/lib/rspectacles/adapter/redis_logger.rb:33:in `log_formatted'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspectacles-0.1.3/lib/rspectacles/formatter/legacy/redis.rb:42:in `example_failed'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:127:in `block in notify'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:126:in `each'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:126:in `notify'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:92:in `example_failed'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:270:in `finish'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:232:in `fail_with_exception'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:398:in `block in fail_filtered_examples'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:398:in `each'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:398:in `fail_filtered_examples'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:402:in `block in fail_filtered_examples'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:400:in `each'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:400:in `fail_filtered_examples'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:376:in `rescue in run'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:381:in `run'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `map'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block in run'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:58:in `report'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
  from /Users/lluchez/.rvm/gems/ruby-2.1.7@xxx/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

I followed the installation steps:
- adding the Gem to the Gemfile
- added the following code into `./.rspec`:
```
--require rspectacles/formatter/legacy/redis
--format RSpectacles::Formatter::Legacy::Redis
```
- ran the following commands:
```
brew install redis
redis-server
rspectacles
```

Please let me know what I'm missing.

Thank you.

**Comment by wheeyls** [comment]
Sorry you ran into this! I'll take a look later this week or this weekend!
